# Generated by Django 5.1.4 on 2026-05-14 16:13

import django.contrib.gis.db.models.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('parcels', '0002_parcel_assessor_fields'),
        ('records', '0005_alter_record_parcel'),
    ]

    operations = [
        migrations.CreateModel(
            name='Project',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('slug', models.SlugField(help_text="URL-safe ID. EngageCOS projects use the page slug (e.g., 'PowersExtension'); manual projects can use any.", max_length=128, unique=True)),
                ('title', models.CharField(max_length=512)),
                ('description', models.TextField(blank=True)),
                ('source', models.CharField(choices=[('engagecos', 'EngageCOS (City of Colorado Springs)'), ('epc', 'El Paso County'), ('manual', 'Manually curated'), ('auto', 'Auto-detected (pending review)')], db_index=True, default='manual', max_length=32)),
                ('source_url', models.URLField(blank=True, max_length=1024)),
                ('source_id', models.CharField(blank=True, max_length=128)),
                ('source_hash', models.CharField(blank=True, max_length=64)),
                ('last_synced_at', models.DateTimeField(blank=True, null=True)),
                ('status', models.CharField(blank=True, db_index=True, max_length=64)),
                ('extent', django.contrib.gis.db.models.fields.GeometryField(blank=True, null=True, srid=4326)),
                ('featured', models.BooleanField(default=False, help_text='Surface on the homepage initiative chip row.')),
                ('auto_generated', models.BooleanField(default=False, help_text='Created by the auto-clustering pipeline. Requires human approval before going public.')),
                ('approved_by', models.CharField(blank=True, max_length=128)),
                ('approved_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('parcels', models.ManyToManyField(blank=True, help_text="A corridor project touches many parcels. M2M lets us answer 'show me every project on this parcel'.", related_name='projects', to='parcels.parcel')),
                ('topic_tags', models.ManyToManyField(blank=True, related_name='projects', to='records.topictag')),
            ],
            options={
                'ordering': ['-featured', '-updated_at'],
                'indexes': [models.Index(fields=['source', 'status'], name='projects_pr_source_32b7b3_idx'), models.Index(fields=['featured', '-updated_at'], name='projects_pr_feature_9886e7_idx')],
            },
        ),
    ]
