# Generated by Django 5.1.4 on 2026-05-13 19:39

import django.contrib.gis.db.models.fields
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='CouncilDistrict',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('district_type', models.CharField(choices=[('city_council', 'City Council'), ('bocc', 'Board of County Commissioners'), ('school_board', 'School Board')], max_length=32)),
                ('number', models.CharField(max_length=8)),
                ('name', models.CharField(blank=True, max_length=128)),
                ('representative', models.CharField(blank=True, max_length=128)),
                ('geometry', django.contrib.gis.db.models.fields.MultiPolygonField(blank=True, null=True, srid=4326)),
            ],
            options={
                'ordering': ['district_type', 'number'],
                'unique_together': {('district_type', 'number')},
            },
        ),
        migrations.CreateModel(
            name='Parcel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('parcel_id', models.CharField(db_index=True, help_text='Assessor parcel ID. Canonical key across all records.', max_length=32, unique=True)),
                ('address', models.CharField(blank=True, help_text='Primary human-readable address, if any.', max_length=255)),
                ('city', models.CharField(blank=True, default='Colorado Springs', max_length=64)),
                ('state', models.CharField(blank=True, default='CO', max_length=2)),
                ('zip_code', models.CharField(blank=True, max_length=10)),
                ('jurisdiction', models.CharField(choices=[('city', 'City of Colorado Springs'), ('county', 'Unincorporated El Paso County'), ('shared', 'Shared / IGA')], default='city', max_length=16)),
                ('geometry', django.contrib.gis.db.models.fields.PolygonField(blank=True, null=True, srid=4326)),
                ('centroid', django.contrib.gis.db.models.fields.PointField(blank=True, null=True, srid=4326)),
                ('acres', models.DecimalField(blank=True, decimal_places=4, max_digits=10, null=True)),
                ('zoning', models.CharField(blank=True, max_length=32)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('council_district', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='parcels', to='parcels.councildistrict')),
            ],
            options={
                'ordering': ['parcel_id'],
            },
        ),
    ]
