#!/usr/bin/env node
// Transforms the Eleventy Labs CitizenConnect permits/licenses/records
// page into a Drupal-droppable partial: namespaced HTML, scoped CSS
// (via @scope), and scoped JS.
//
// Source of truth:  ../city-permits-licenses-records.njk
// Output:           ./dist/{citizenconnect.html, .css, .js}
//                   ./preview/index.html  (self-contained demo)
//
// Run:  node microsites/city/CitizenConnect/dversion/build.mjs

import { readFileSync, writeFileSync, mkdirSync } from 'node:fs';
import { dirname, resolve } from 'node:path';
import { fileURLToPath } from 'node:url';

const HERE = dirname(fileURLToPath(import.meta.url));
const SRC = resolve(HERE, '..', 'city-permits-licenses-records.njk');
const DIST = resolve(HERE, 'dist');
const PREVIEW = resolve(HERE, 'preview');

const NS = 'cc-citizenconnect';
const PRETTY_NAME = 'CitizenConnect — permits, licenses & records';
const FILE_BASE = 'citizenconnect';

const src = readFileSync(SRC, 'utf8');

// ---------------------------------------------------------------- 1. front matter
const fmEnd = src.indexOf('---', 3);
if (fmEnd < 0) throw new Error('No front matter terminator found');
const afterFm = src.slice(fmEnd + 3);

// ---------------------------------------------------------------- 2. extract <style> blocks
const styleBlocks = [];
const styleRe = /<style>([\s\S]*?)<\/style>/g;
let m;
while ((m = styleRe.exec(afterFm)) !== null) styleBlocks.push(m[1]);

// ---------------------------------------------------------------- 3. extract <script> blocks
const scriptBlocks = [];
const scriptRe = /<script>([\s\S]*?)<\/script>/g;
while ((m = scriptRe.exec(afterFm)) !== null) scriptBlocks.push(m[1]);

// ---------------------------------------------------------------- 4. body markup
let body = afterFm
  .replace(styleRe, '')
  .replace(scriptRe, '')
  .trim();

// This source has no inline <header>/<footer> — site.njk would have
// supplied those — so nothing to strip.

// ---------------------------------------------------------------- 5. CSS transform
let css = styleBlocks.join('\n\n/* --- */\n\n');

// 5a. Hoist any @import url(...) statements out of the source CSS to the
// top of the stylesheet. @import is invalid inside @scope and must
// precede all other rules; we also keep them so themed mode can use
// the source's chosen webfonts.
const imports = [];
css = css.replace(/@import\s+url\([^)]+\)\s*;?/g, (match) => {
  imports.push(match.trim().replace(/;?$/, ';'));
  return '';
});

// 5b. Promote :root custom properties onto the namespace root so they
// are scope-local. Drupal's :root vars stay untouched.
css = css.replace(/:root\s*\{/g, `.${NS} {`);

// 5c. Drop bare html/body resets that would otherwise live inside the
// scope as no-ops or surprises.
css = css.replace(/\n\s*html\s*\{[^}]*\}/g, '');
css = css.replace(/\n\s*body\s*\{[^}]*\}/g, '');

const scopedCss = [
  `/* Scoped to .${NS} via CSS @scope. Generated by build.mjs from`,
  `   city-permits-licenses-records.njk — do not edit dist/ by hand. */`,
  ``,
  ...imports,
  imports.length ? '' : null,
  `@scope (.${NS}) {`,
  css.trim(),
  `}`,
  ``,
  `/* Default (un-themed) mode: redefine typography and base text tokens`,
  `   to "inherit" so descendant rules like  font-family: var(--body)`,
  `   resolve up to the host page's font and color. The CitizenConnect`,
  `   palette (--navy, --gold, --cream, etc.) stays so the portal keeps`,
  `   its visual identity. Add  .${NS}--themed  to opt into the full`,
  `   cheetochopsticks Inter / Libre Baskerville typography. */`,
  `.${NS}:not(.${NS}--themed) {`,
  `  --display: inherit;`,
  `  --body: inherit;`,
  `  --serif: inherit;`,
  `  --sans: inherit;`,
  `  --mono: ui-monospace, monospace;`,
  `  --ink: inherit;`,
  `  --ink-soft: inherit;`,
  `  --ink-faint: inherit;`,
  `  font-family: inherit;`,
  `  color: inherit;`,
  `  background: transparent;`,
  `}`,
  ``,
].filter((l) => l !== null).join('\n');

// ---------------------------------------------------------------- 6. JS transform
let js = scriptBlocks.join('\n\n// --- next script block ---\n\n');

// Detect any inline event-attribute references so we can expose those
// functions on window. (CitizenConnect currently uses none, but this
// keeps the build resilient if future edits add them.)
const handlerNames = new Set();
const handlerRe = /\son[a-z]+\s*=\s*"([a-zA-Z_$][\w$]*)\(/g;
const partialBodyForHandlerScan = body;
let h;
while ((h = handlerRe.exec(partialBodyForHandlerScan)) !== null) handlerNames.add(h[1]);

const exposeLines = [...handlerNames].map((n) => `  window.${n} = ${n};`);

const scopedJs = [
  `// Scoped to .${NS}. Generated by build.mjs — do not edit dist/ by hand.`,
  `(function () {`,
  `  const ROOT = document.querySelector('.${NS}');`,
  `  if (!ROOT) return;`,
  ``,
  `  // Re-bind document.* lookups to resolve against the partial root,`,
  `  // so IDs and class selectors can't collide with the host Drupal page.`,
  `  const document = new Proxy(window.document, {`,
  `    get(target, prop) {`,
  `      if (prop === 'getElementById') return (id) => ROOT.querySelector('#' + CSS.escape(id));`,
  `      if (prop === 'querySelector') return (sel) => ROOT.querySelector(sel);`,
  `      if (prop === 'querySelectorAll') return (sel) => ROOT.querySelectorAll(sel);`,
  `      const v = target[prop];`,
  `      return typeof v === 'function' ? v.bind(target) : v;`,
  `    },`,
  `  });`,
  ``,
  js.trim(),
  ``,
  exposeLines.length
    ? `  // Expose handlers used by inline on* attributes (the IIFE would otherwise hide them).\n${exposeLines.join('\n')}`
    : `  // (No inline on* handlers detected — nothing to expose on window.)`,
  `})();`,
  ``,
].join('\n');

// ---------------------------------------------------------------- 7. HTML partial
const partial = [
  `<!-- ${PRETTY_NAME} — Drupal partial.`,
  `     Generated by build.mjs from city-permits-licenses-records.njk.`,
  `     Drop into a Drupal Custom Block (Source/HTML view) and attach`,
  `     ${FILE_BASE}.css and ${FILE_BASE}.js as a library. -->`,
  ``,
  `<!-- Add  ${NS}--themed  to the root for the cheetochopsticks palette;`,
  `     omit it to inherit the host site's typography and color. -->`,
  `<div class="${NS}">`,
  body.trim(),
  `</div>`,
  ``,
].join('\n');

// ---------------------------------------------------------------- 8. preview harness
const previewHtml = [
  `<!doctype html>`,
  `<html lang="en">`,
  `<head>`,
  `<meta charset="utf-8">`,
  `<title>${PRETTY_NAME} DVersion — preview harness</title>`,
  `<meta name="viewport" content="width=device-width, initial-scale=1">`,
  `<style>`,
  `  :root {`,
  `    --host-bg: #f4f1ec;`,
  `    --host-fg: #1d2733;`,
  `    --host-accent: #1a4f8b;`,
  `    --host-rule: #c9c2b6;`,
  `  }`,
  `  html, body { margin: 0; background: var(--host-bg); color: var(--host-fg);`,
  `               font: 16px/1.55 'Times New Roman', Georgia, serif; }`,
  `  .host-bar { background: var(--host-accent); color: #fff; padding: 12px 20px; font-size: 14px; }`,
  `  .host-nav { background: #fff; border-bottom: 1px solid var(--host-rule); padding: 14px 20px; }`,
  `  .host-nav strong { font-size: 18px; color: var(--host-accent); }`,
  `  .host-content { max-width: 1240px; margin: 0 auto; padding: 28px 20px; }`,
  `  .host-content > h1 { font: 30px/1.2 'Times New Roman', Georgia, serif; margin: 0 0 8px; }`,
  `  .host-content > p { margin: 0 0 18px; max-width: 64ch; }`,
  `  .host-toggle { display: inline-flex; gap: 8px; margin: 12px 0 24px; padding: 6px;`,
  `                 border: 1px solid var(--host-rule); border-radius: 6px; background: #fff; }`,
  `  .host-toggle button { border: 0; padding: 6px 12px; cursor: pointer; font: inherit;`,
  `                        color: var(--host-fg); background: transparent; border-radius: 4px; }`,
  `  .host-toggle button[aria-pressed="true"] { background: var(--host-accent); color: #fff; }`,
  `  .host-footer { border-top: 1px solid var(--host-rule); padding: 18px 20px;`,
  `                 color: #555; font-size: 13px; text-align: center; }`,
  `</style>`,
  `<style id="${FILE_BASE}-css">`,
  scopedCss,
  `</style>`,
  `</head>`,
  `<body>`,
  `<div class="host-bar">cheetochopsticks.gov · simulated Drupal host page</div>`,
  `<div class="host-nav"><strong>City of Colorado Springs</strong> &nbsp; · &nbsp; CitizenConnect</div>`,
  `<main class="host-content">`,
  `  <h1>Permits, Licenses &amp; Records (Drupal-hosted)</h1>`,
  `  <p>The block below is the <code>${NS}</code> partial. Use the toggle to compare default (inherit host typography) vs. themed (cheetochopsticks).</p>`,
  `  <div class="host-toggle" role="group" aria-label="Theme mode">`,
  `    <button id="mode-inherit" aria-pressed="true">Default (inherit host)</button>`,
  `    <button id="mode-themed" aria-pressed="false">Themed (cheetochopsticks)</button>`,
  `  </div>`,
  partial.trim(),
  `</main>`,
  `<div class="host-footer">© Simulated Drupal host page · the partial above is fully scoped.</div>`,
  `<script id="${FILE_BASE}-js">`,
  scopedJs,
  `</script>`,
  `<script>`,
  `(function () {`,
  `  const root = () => document.querySelector('.${NS}');`,
  `  const setMode = (themed) => {`,
  `    const r = root(); if (!r) return;`,
  `    r.classList.toggle('${NS}--themed', themed);`,
  `    document.getElementById('mode-inherit').setAttribute('aria-pressed', String(!themed));`,
  `    document.getElementById('mode-themed').setAttribute('aria-pressed', String(themed));`,
  `  };`,
  `  document.getElementById('mode-inherit').addEventListener('click', () => setMode(false));`,
  `  document.getElementById('mode-themed').addEventListener('click', () => setMode(true));`,
  `})();`,
  `</script>`,
  `</body>`,
  `</html>`,
  ``,
].join('\n');

// ---------------------------------------------------------------- 9. write
mkdirSync(DIST, { recursive: true });
writeFileSync(resolve(DIST, `${FILE_BASE}.html`), partial);
writeFileSync(resolve(DIST, `${FILE_BASE}.css`), scopedCss);
writeFileSync(resolve(DIST, `${FILE_BASE}.js`), scopedJs);

mkdirSync(PREVIEW, { recursive: true });
writeFileSync(resolve(PREVIEW, 'index.html'), previewHtml);

console.log(
  `${PRETTY_NAME} DVersion built:\n` +
  `  ${DIST}/${FILE_BASE}.html  (${partial.length.toLocaleString()} bytes)\n` +
  `  ${DIST}/${FILE_BASE}.css   (${scopedCss.length.toLocaleString()} bytes)\n` +
  `  ${DIST}/${FILE_BASE}.js    (${scopedJs.length.toLocaleString()} bytes)\n` +
  `  ${PREVIEW}/index.html  (${previewHtml.length.toLocaleString()} bytes, self-contained)\n` +
  `  hoisted ${imports.length} @import statement(s); exposed ${handlerNames.size} inline handler(s) on window.`,
);
