# Generated by Django 5.1.4 on 2026-05-13 19:39

import django.contrib.gis.db.models.fields
import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('parcels', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Record',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('record_id', models.CharField(db_index=True, help_text='External ID from the originating system, or a generated UUID if internal.', max_length=64, unique=True)),
                ('record_type', models.CharField(choices=[('permit', 'Permit'), ('project', 'Project'), ('request', 'Service Request'), ('meeting_item', 'Meeting Item'), ('financial', 'Financial Allocation'), ('inspection', 'Inspection'), ('violation', 'Violation / Code Enforcement'), ('other', 'Other')], max_length=32)),
                ('title', models.CharField(max_length=512)),
                ('description', models.TextField(blank=True)),
                ('status', models.CharField(choices=[('open', 'Open'), ('in_review', 'In Review'), ('in_progress', 'In Progress'), ('awaiting_action', 'Awaiting Action'), ('scheduled', 'Scheduled'), ('completed', 'Completed'), ('closed', 'Closed'), ('denied', 'Denied'), ('withdrawn', 'Withdrawn')], default='open', max_length=32)),
                ('owner_department', models.CharField(blank=True, help_text='Which department currently owns this record.', max_length=128)),
                ('owner_person', models.CharField(blank=True, max_length=128)),
                ('source_system', models.CharField(blank=True, help_text='Where this record was sourced from (BoardDocs, GoCOS, PPRBD, manual, etc.)', max_length=64)),
                ('source_url', models.URLField(blank=True, max_length=1024)),
                ('plain_summary', models.TextField(blank=True, help_text='Human-readable, jargon-free summary. AI-drafted, human-reviewed.')),
                ('point_location', django.contrib.gis.db.models.fields.PointField(blank=True, null=True, srid=4326)),
                ('occurred_at', models.DateTimeField(blank=True, help_text='When the underlying event happened (e.g., the meeting date, the permit application date). May differ from created_at, which is when the record entered this system.', null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('connected_records', models.ManyToManyField(blank=True, help_text='Other records linked to this one.', to='records.record')),
                ('parcel', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='records', to='parcels.parcel')),
            ],
            options={
                'ordering': ['-updated_at'],
            },
        ),
        migrations.CreateModel(
            name='RecordHistory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('from_status', models.CharField(blank=True, max_length=32)),
                ('to_status', models.CharField(max_length=32)),
                ('changed_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('changed_by', models.CharField(blank=True, max_length=128)),
                ('note', models.TextField(blank=True)),
                ('record', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='history', to='records.record')),
            ],
            options={
                'verbose_name_plural': 'Record history',
                'ordering': ['-changed_at'],
            },
        ),
        migrations.AddIndex(
            model_name='record',
            index=models.Index(fields=['record_type', 'status'], name='records_rec_record__da2202_idx'),
        ),
        migrations.AddIndex(
            model_name='record',
            index=models.Index(fields=['occurred_at'], name='records_rec_occurre_10c5b7_idx'),
        ),
    ]
