# Generated by Django 5.1.4 on 2026-05-14 05:33

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('parcels', '0001_initial'),
        ('records', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='TopicTag',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('slug', models.SlugField(max_length=64, unique=True)),
                ('label', models.CharField(max_length=128)),
                ('description', models.TextField(blank=True)),
            ],
            options={
                'ordering': ['label'],
            },
        ),
        migrations.AddField(
            model_name='record',
            name='enriched_at',
            field=models.DateTimeField(blank=True, help_text='When the LLM enrichment pipeline last generated plain_summary + topic_tags for this record.', null=True),
        ),
        migrations.AddField(
            model_name='record',
            name='last_synced_at',
            field=models.DateTimeField(blank=True, help_text='When the ingest pipeline last fetched this record from source. Distinct from updated_at, which fires on any field change.', null=True),
        ),
        migrations.AddField(
            model_name='record',
            name='source_hash',
            field=models.CharField(blank=True, help_text='SHA-256 of the normalized source payload at last ingest. Used to skip unchanged rows and gate LLM enrichment.', max_length=64),
        ),
        migrations.AddField(
            model_name='record',
            name='source_id',
            field=models.CharField(blank=True, help_text="The record's ID inside the source system. Together with source_system, uniquely identifies an upstream row for upsert. Distinct from record_id, which is our internal key.", max_length=128),
        ),
        migrations.AlterField(
            model_name='record',
            name='source_system',
            field=models.CharField(blank=True, db_index=True, help_text='Where this record was sourced from (epc_parcels, cspd_socrata, accela_cos, agendasuite, etc.)', max_length=64),
        ),
        migrations.CreateModel(
            name='IngestRun',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('source', models.CharField(db_index=True, help_text="Source identifier — matches Record.source_system (e.g., 'epc_parcels', 'cspd_socrata').", max_length=64)),
                ('started_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('finished_at', models.DateTimeField(blank=True, null=True)),
                ('status', models.CharField(choices=[('running', 'Running'), ('success', 'Success'), ('partial', 'Partial (some rows failed)'), ('failed', 'Failed')], default='running', max_length=16)),
                ('records_created', models.PositiveIntegerField(default=0)),
                ('records_updated', models.PositiveIntegerField(default=0)),
                ('records_skipped', models.PositiveIntegerField(default=0)),
                ('records_failed', models.PositiveIntegerField(default=0)),
                ('error', models.TextField(blank=True)),
                ('notes', models.TextField(blank=True)),
            ],
            options={
                'ordering': ['-started_at'],
                'indexes': [models.Index(fields=['source', '-started_at'], name='records_ing_source_963683_idx')],
            },
        ),
        migrations.AddField(
            model_name='record',
            name='topic_tags',
            field=models.ManyToManyField(blank=True, help_text='Soft topic tags assigned by enrichment. Closed taxonomy.', related_name='records', to='records.topictag'),
        ),
        migrations.AddIndex(
            model_name='record',
            index=models.Index(fields=['source_system', 'source_id'], name='records_rec_source__400464_idx'),
        ),
        migrations.AddConstraint(
            model_name='record',
            constraint=models.UniqueConstraint(condition=models.Q(models.Q(('source_system', ''), _negated=True), models.Q(('source_id', ''), _negated=True)), fields=('source_system', 'source_id'), name='uniq_source_system_id'),
        ),
    ]
