# Generated by Django 5.1.4 on 2026-05-14 05:44

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('records', '0003_seed_topic_tags'),
    ]

    operations = [
        migrations.CreateModel(
            name='LLMCallLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('purpose', models.CharField(choices=[('enrich', 'Record enrichment'), ('taxonomy_discover', 'Source taxonomy discovery'), ('other', 'Other')], db_index=True, max_length=32)),
                ('model', models.CharField(blank=True, max_length=64)),
                ('input_tokens', models.PositiveIntegerField(default=0)),
                ('output_tokens', models.PositiveIntegerField(default=0)),
                ('cache_read_tokens', models.PositiveIntegerField(default=0)),
                ('cache_write_tokens', models.PositiveIntegerField(default=0)),
                ('cost_usd', models.DecimalField(blank=True, decimal_places=6, help_text='Estimated cost in USD, computed from token counts at ingest time.', max_digits=10, null=True)),
                ('error', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('record', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='llm_calls', to='records.record')),
            ],
            options={
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['purpose', '-created_at'], name='records_llm_purpose_58465b_idx')],
            },
        ),
    ]
