# Generated by Django 5.1.4 on 2026-05-14 05:51

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('parcels', '0001_initial'),
        ('records', '0004_llmcalllog'),
    ]

    operations = [
        migrations.AlterField(
            model_name='record',
            name='parcel',
            field=models.ForeignKey(blank=True, help_text="Most records belong to a parcel. Some don't — a city-wide policy meeting item, an agency-level financial allocation. Null records still appear in jurisdictional views, just not on any parcel detail page.", null=True, on_delete=django.db.models.deletion.PROTECT, related_name='records', to='parcels.parcel'),
        ),
    ]
