# Generated by Django 5.1.4 on 2026-05-14 16:13

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0001_initial'),
        ('records', '0005_alter_record_parcel'),
    ]

    operations = [
        migrations.AddField(
            model_name='record',
            name='project',
            field=models.ForeignKey(blank=True, help_text='Optional grouping under a multi-event project (capital project, planning initiative). Lets us reconstruct the RFP → award → milestones lifecycle.', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='records', to='projects.project'),
        ),
        migrations.AlterField(
            model_name='record',
            name='record_type',
            field=models.CharField(choices=[('permit', 'Permit'), ('project', 'Project'), ('request', 'Service Request'), ('meeting_item', 'Meeting Item'), ('financial', 'Financial Allocation'), ('inspection', 'Inspection'), ('violation', 'Violation / Code Enforcement'), ('solicitation', 'Solicitation / RFP'), ('award', 'Contract Award'), ('milestone', 'Project Milestone'), ('other', 'Other')], max_length=32),
        ),
    ]
