# Generated by Django 5.1.4 on 2026-05-13 19:39

import django.contrib.postgres.indexes
import django.contrib.postgres.search
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('records', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Document',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('file', models.FileField(upload_to='documents/%Y/%m/')),
                ('filename', models.CharField(max_length=512)),
                ('document_type', models.CharField(choices=[('pdf', 'PDF'), ('image', 'Image'), ('doc', 'Word Document'), ('xls', 'Spreadsheet'), ('other', 'Other')], default='pdf', max_length=16)),
                ('extracted_text', models.TextField(blank=True)),
                ('search_vector', django.contrib.postgres.search.SearchVectorField(blank=True, null=True)),
                ('page_count', models.IntegerField(blank=True, null=True)),
                ('byte_size', models.BigIntegerField(blank=True, null=True)),
                ('source_url', models.URLField(blank=True, max_length=1024)),
                ('uploaded_at', models.DateTimeField(auto_now_add=True)),
                ('record', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='documents', to='records.record')),
            ],
            options={
                'ordering': ['-uploaded_at'],
                'indexes': [django.contrib.postgres.indexes.GinIndex(fields=['search_vector'], name='documents_d_search__05a045_gin')],
            },
        ),
    ]
