#!/usr/bin/env node
// Transforms the Eleventy Labs forestry page into a Drupal-droppable
// partial: namespaced HTML, scoped CSS (via @scope), and scoped JS.
//
// Source of truth:  ../trees-of-colorado-springs.njk
// Output:           ./dist/{forestry.html, forestry.css, forestry.js}
//
// Run:  node microsites/city/forestry/dversion/build.mjs

import { readFileSync, writeFileSync, mkdirSync } from 'node:fs';
import { dirname, resolve } from 'node:path';
import { fileURLToPath } from 'node:url';

const HERE = dirname(fileURLToPath(import.meta.url));
const SRC = resolve(HERE, '..', 'trees-of-colorado-springs.njk');
const DIST = resolve(HERE, 'dist');

const NS = 'cc-forestry';

const src = readFileSync(SRC, 'utf8');

// ---------------------------------------------------------------- 1. front matter
const fmEnd = src.indexOf('---', 3);
if (fmEnd < 0) throw new Error('No front matter terminator found');
const afterFm = src.slice(fmEnd + 3);

// ---------------------------------------------------------------- 2. extract <style> blocks
const styleBlocks = [];
const styleRe = /<style>([\s\S]*?)<\/style>/g;
let m;
while ((m = styleRe.exec(afterFm)) !== null) styleBlocks.push(m[1]);

// ---------------------------------------------------------------- 3. extract <script> blocks
const scriptBlocks = [];
const scriptRe = /<script>([\s\S]*?)<\/script>/g;
while ((m = scriptRe.exec(afterFm)) !== null) scriptBlocks.push(m[1]);

// ---------------------------------------------------------------- 4. body markup
// Strip <style>...</style> and <script>...</script> from afterFm.
let body = afterFm
  .replace(styleRe, '')
  .replace(scriptRe, '')
  .trim();

// Drop the site header (Drupal owns top-of-page chrome) and the
// site-level footer (Drupal owns bottom-of-page chrome). Keep the
// forestry-specific content and the SVG sprite.
body = body.replace(
  /<!-- =+\s*Site header[\s\S]*?<\/header>/,
  '',
);
body = body.replace(
  /<!-- =+\s*Forestry-specific contact footer[\s\S]*?<\/footer>/,
  '',
);

// ---------------------------------------------------------------- 5. CSS transform
let css = styleBlocks.join('\n\n/* --- */\n\n');

// Promote :root custom properties onto the namespace root so they are
// scope-local. Drupal's :root vars stay untouched; ours layer on top
// only inside .cc-forestry.
css = css.replace(/:root\s*\{/g, `.${NS} {`);

// Drop the global resets that would clobber Drupal's body/html.
// (`* { ... }` survives only inside @scope, where it scopes to descendants.)
css = css.replace(/\n\s*html\s*\{[^}]*\}/g, '');
css = css.replace(/\n\s*body\s*\{[^}]*\}/g, '');

// Wrap the whole thing in @scope so universal/element selectors are
// confined to descendants of .cc-forestry. (CSS @scope is supported in
// modern Chrome/Edge/Safari/Firefox; Drupal sites typically only need
// these.)
const scopedCss = [
  `/* Scoped to .${NS} via CSS @scope. Generated by build.mjs from`,
  `   trees-of-colorado-springs.njk — do not edit dist/ by hand. */`,
  ``,
  `@scope (.${NS}) {`,
  css.trim(),
  `}`,
  ``,
  `/* Default (un-themed) mode: redefine the typography and base text`,
  `   tokens to "inherit" so descendant rules like  font-family: var(--body)`,
  `   resolve up to the host page's font and color. The forestry brand`,
  `   accents (--forest-deep, --rust, --gold, --paper, etc.) stay so the`,
  `   catalog keeps its visual identity. Add  .${NS}--themed  to opt`,
  `   into the full cheetochopsticks Fraunces/Public Sans typography. */`,
  `.${NS}:not(.${NS}--themed) {`,
  `  --display: inherit;`,
  `  --body: inherit;`,
  `  --mono: ui-monospace, monospace;`,
  `  --ink: inherit;`,
  `  --ink-soft: inherit;`,
  `  --ink-faint: inherit;`,
  `  font-family: inherit;`,
  `  color: inherit;`,
  `  background: transparent;`,
  `}`,
  ``,
].join('\n');

// ---------------------------------------------------------------- 6. JS transform
let js = scriptBlocks.join('\n\n// --- next script block ---\n\n');

// Wrap in an IIFE rooted at the namespace element so getElementById /
// querySelector calls don't escape the partial. Drupal pages may have
// their own #search, #grid, etc. — this keeps us self-contained.
const scopedJs = [
  `// Scoped to .${NS}. Generated by build.mjs — do not edit dist/ by hand.`,
  `(function () {`,
  `  const ROOT = document.querySelector('.${NS}');`,
  `  if (!ROOT) return;`,
  ``,
  `  // Re-bind the document API to the partial root. Anything inside`,
  `  // the original code that reaches for document.getElementById /`,
  `  // .querySelector / .querySelectorAll resolves against ROOT instead.`,
  `  const document = new Proxy(window.document, {`,
  `    get(target, prop) {`,
  `      if (prop === 'getElementById') return (id) => ROOT.querySelector('#' + CSS.escape(id));`,
  `      if (prop === 'querySelector') return (sel) => ROOT.querySelector(sel);`,
  `      if (prop === 'querySelectorAll') return (sel) => ROOT.querySelectorAll(sel);`,
  `      const v = target[prop];`,
  `      return typeof v === 'function' ? v.bind(target) : v;`,
  `    },`,
  `  });`,
  ``,
  js.trim(),
  ``,
  `  // Expose handlers used by inline onclick/onsubmit attributes in the`,
  `  // partial. The IIFE would otherwise hide them from HTML attribute scope.`,
  `  window.openModal = openModal;`,
  `  window.closeModal = closeModal;`,
  `  window.submitRec = submitRec;`,
  `  window.copyRecToClipboard = copyRecToClipboard;`,
  `})();`,
  ``,
].join('\n');

// ---------------------------------------------------------------- 7. HTML partial
const partial = [
  `<!-- Trees for Colorado Springs — Drupal partial.`,
  `     Generated by build.mjs from trees-of-colorado-springs.njk.`,
  `     Drop into a Drupal Custom Block (Source/HTML view) and attach`,
  `     forestry.css and forestry.js as a library. -->`,
  ``,
  `<!-- Add  ${NS}--themed  to the root for the cheetochopsticks palette;`,
  `     omit it to inherit the host site's typography and color. -->`,
  `<div class="${NS}">`,
  body.trim(),
  `</div>`,
  ``,
].join('\n');

// ---------------------------------------------------------------- 8. preview harness (self-contained, no fetch)
// Simulates a Drupal host page (different fonts/colors so we can see
// either-direction style leakage) and embeds the partial inline. No
// network requests; opens directly via file:// in any preview panel.
const previewHtml = [
  `<!doctype html>`,
  `<html lang="en">`,
  `<head>`,
  `<meta charset="utf-8">`,
  `<title>Forestry DVersion — preview harness</title>`,
  `<meta name="viewport" content="width=device-width, initial-scale=1">`,
  `<style>`,
  `  :root {`,
  `    --host-bg: #f4f1ec;`,
  `    --host-fg: #1d2733;`,
  `    --host-accent: #1a4f8b;`,
  `    --host-rule: #c9c2b6;`,
  `  }`,
  `  html, body { margin: 0; background: var(--host-bg); color: var(--host-fg);`,
  `               font: 16px/1.55 'Times New Roman', Georgia, serif; }`,
  `  .host-bar { background: var(--host-accent); color: #fff; padding: 12px 20px; font-size: 14px; }`,
  `  .host-nav { background: #fff; border-bottom: 1px solid var(--host-rule); padding: 14px 20px; }`,
  `  .host-nav strong { font-size: 18px; color: var(--host-accent); }`,
  `  .host-content { max-width: 1240px; margin: 0 auto; padding: 28px 20px; }`,
  `  .host-content > h1 { font: 30px/1.2 'Times New Roman', Georgia, serif; margin: 0 0 8px; }`,
  `  .host-content > p { margin: 0 0 18px; max-width: 64ch; }`,
  `  .host-toggle { display: inline-flex; gap: 8px; margin: 12px 0 24px; padding: 6px;`,
  `                 border: 1px solid var(--host-rule); border-radius: 6px; background: #fff; }`,
  `  .host-toggle button { border: 0; padding: 6px 12px; cursor: pointer; font: inherit;`,
  `                        color: var(--host-fg); background: transparent; border-radius: 4px; }`,
  `  .host-toggle button[aria-pressed="true"] { background: var(--host-accent); color: #fff; }`,
  `  .host-footer { border-top: 1px solid var(--host-rule); padding: 18px 20px;`,
  `                 color: #555; font-size: 13px; text-align: center; }`,
  `</style>`,
  `<style id="forestry-css">`,
  scopedCss,
  `</style>`,
  `<link rel="preconnect" href="https://fonts.googleapis.com">`,
  `<link rel="preconnect" href="https://fonts.gstatic.com" crossorigin>`,
  `<link href="https://fonts.googleapis.com/css2?family=Fraunces:ital,opsz,wght@0,9..144,400;0,9..144,500;0,9..144,600;0,9..144,700;0,9..144,800;1,9..144,500&family=Public+Sans:wght@300;400;500;600;700&display=swap" rel="stylesheet">`,
  `</head>`,
  `<body>`,
  `<div class="host-bar">cheetochopsticks.gov · simulated Drupal host page</div>`,
  `<div class="host-nav"><strong>City of Colorado Springs</strong> &nbsp; · &nbsp; Forestry Division</div>`,
  `<main class="host-content">`,
  `  <h1>Tree Reference (Drupal-hosted)</h1>`,
  `  <p>The block below is the <code>${NS}</code> partial. Use the toggle to compare default (inherit host typography) vs. themed (cheetochopsticks).</p>`,
  `  <div class="host-toggle" role="group" aria-label="Theme mode">`,
  `    <button id="mode-inherit" aria-pressed="true">Default (inherit host)</button>`,
  `    <button id="mode-themed" aria-pressed="false">Themed (cheetochopsticks)</button>`,
  `  </div>`,
  partial.trim(),
  `</main>`,
  `<div class="host-footer">© Simulated Drupal host page · the partial above is fully scoped.</div>`,
  `<script id="forestry-js">`,
  scopedJs,
  `</script>`,
  `<script>`,
  `(function () {`,
  `  const root = () => document.querySelector('.${NS}');`,
  `  const setMode = (themed) => {`,
  `    const r = root(); if (!r) return;`,
  `    r.classList.toggle('${NS}--themed', themed);`,
  `    document.getElementById('mode-inherit').setAttribute('aria-pressed', String(!themed));`,
  `    document.getElementById('mode-themed').setAttribute('aria-pressed', String(themed));`,
  `  };`,
  `  document.getElementById('mode-inherit').addEventListener('click', () => setMode(false));`,
  `  document.getElementById('mode-themed').addEventListener('click', () => setMode(true));`,
  `})();`,
  `</script>`,
  `</body>`,
  `</html>`,
  ``,
].join('\n');

// ---------------------------------------------------------------- 9. write
mkdirSync(DIST, { recursive: true });
writeFileSync(resolve(DIST, 'forestry.html'), partial);
writeFileSync(resolve(DIST, 'forestry.css'), scopedCss);
writeFileSync(resolve(DIST, 'forestry.js'), scopedJs);

const PREVIEW = resolve(HERE, 'preview');
mkdirSync(PREVIEW, { recursive: true });
writeFileSync(resolve(PREVIEW, 'index.html'), previewHtml);

console.log(
  `forestry DVersion built:\n` +
  `  ${DIST}/forestry.html  (${partial.length.toLocaleString()} bytes)\n` +
  `  ${DIST}/forestry.css   (${scopedCss.length.toLocaleString()} bytes)\n` +
  `  ${DIST}/forestry.js    (${scopedJs.length.toLocaleString()} bytes)\n` +
  `  ${PREVIEW}/index.html  (${previewHtml.length.toLocaleString()} bytes, self-contained)`,
);
