// AUTO-GENERATED by worker/generate-catalog.mjs. Do not edit by hand.
// Regenerate with: node --experimental-strip-types worker/generate-catalog.mjs

export interface CatalogTopic {
  id: string;
  name: string;
  group: string;
  intent: string;
  jurisdiction: string;
  destination: string;
  description: string;
  synonyms: string[];
}

export const CATALOG: CatalogTopic[] = [
  {
    "id": "61591",
    "name": "Accessible / ADA Parking Enforcement",
    "group": "Accessibility and Language Access",
    "intent": "report",
    "jurisdiction": "city",
    "destination": "form",
    "description": "",
    "synonyms": [
      "ada parking",
      "handicap parking",
      "accessible parking"
    ]
  },
  {
    "id": "61723",
    "name": "General Accessibility / ADA Issues",
    "group": "Accessibility and Language Access",
    "intent": "contact",
    "jurisdiction": "city",
    "destination": "form",
    "description": "",
    "synonyms": [
      "ada",
      "accessibility",
      "wheelchair",
      "disability accommodation"
    ]
  },
  {
    "id": "61738",
    "name": "Language Access/Discrimination: Title VI of the Civil Rights Act",
    "group": "Accessibility and Language Access",
    "intent": "contact",
    "jurisdiction": "city",
    "destination": "form",
    "description": "",
    "synonyms": [
      "language access",
      "translation",
      "interpreter",
      "title vi",
      "discrimination"
    ]
  },
  {
    "id": "61745",
    "name": "Mountain Metro Transit Accommodation (bus, bus stops, mobility)",
    "group": "Accessibility and Language Access",
    "intent": "contact",
    "jurisdiction": "city",
    "destination": "form",
    "description": "",
    "synonyms": []
  },
  {
    "id": "61807",
    "name": "Web Accessibility",
    "group": "Accessibility and Language Access",
    "intent": "contact",
    "jurisdiction": "city",
    "destination": "form",
    "description": "",
    "synonyms": []
  },
  {
    "id": "61640",
    "name": "City Attorney's Office",
    "group": "Contact A City Department",
    "intent": "contact",
    "jurisdiction": "city",
    "destination": "form",
    "description": "",
    "synonyms": []
  },
  {
    "id": "61641",
    "name": "City Auditor",
    "group": "Contact A City Department",
    "intent": "contact",
    "jurisdiction": "city",
    "destination": "form",
    "description": "",
    "synonyms": []
  },
  {
    "id": "61642",
    "name": "City Clerk",
    "group": "Contact A City Department",
    "intent": "contact",
    "jurisdiction": "city",
    "destination": "form",
    "description": "",
    "synonyms": []
  },
  {
    "id": "61643",
    "name": "City Communications",
    "group": "Contact A City Department",
    "intent": "contact",
    "jurisdiction": "city",
    "destination": "form",
    "description": "",
    "synonyms": []
  },
  {
    "id": "61644",
    "name": "City Council",
    "group": "Contact A City Department",
    "intent": "contact",
    "jurisdiction": "city",
    "destination": "form",
    "description": "",
    "synonyms": []
  },
  {
    "id": "61645",
    "name": "City Engineering",
    "group": "Contact A City Department",
    "intent": "contact",
    "jurisdiction": "city",
    "destination": "form",
    "description": "",
    "synonyms": []
  },
  {
    "id": "61646",
    "name": "City Finance Department",
    "group": "Contact A City Department",
    "intent": "contact",
    "jurisdiction": "city",
    "destination": "form",
    "description": "",
    "synonyms": []
  },
  {
    "id": "70124",
    "name": "City Forestry",
    "group": "Contact A City Department",
    "intent": "contact",
    "jurisdiction": "city",
    "destination": "form",
    "description": "Contact City Forestry with general questions or comments. For tree-specific requests, please look under the \"Trees\" category in the request menu.",
    "synonyms": []
  },
  {
    "id": "61697",
    "name": "COS Airport",
    "group": "Contact A City Department",
    "intent": "contact",
    "jurisdiction": "city",
    "destination": "form",
    "description": "",
    "synonyms": []
  },
  {
    "id": "61703",
    "name": "Cultural Services",
    "group": "Contact A City Department",
    "intent": "contact",
    "jurisdiction": "city",
    "destination": "form",
    "description": "",
    "synonyms": []
  },
  {
    "id": "61710",
    "name": "Economic Development",
    "group": "Contact A City Department",
    "intent": "contact",
    "jurisdiction": "city",
    "destination": "form",
    "description": "",
    "synonyms": []
  },
  {
    "id": "61733",
    "name": "Housing and Homelessness Response",
    "group": "Contact A City Department",
    "intent": "contact",
    "jurisdiction": "city",
    "destination": "form",
    "description": "",
    "synonyms": []
  },
  {
    "id": "61743",
    "name": "Mayor's Office",
    "group": "Contact A City Department",
    "intent": "contact",
    "jurisdiction": "city",
    "destination": "form",
    "description": "",
    "synonyms": []
  },
  {
    "id": "61747",
    "name": "Mountain Metro Transit (MMT)",
    "group": "Contact A City Department",
    "intent": "contact",
    "jurisdiction": "city",
    "destination": "form",
    "description": "",
    "synonyms": []
  },
  {
    "id": "61746",
    "name": "Mountain Metro Transit Compliment or Complaint",
    "group": "Contact A City Department",
    "intent": "report",
    "jurisdiction": "city",
    "destination": "form",
    "description": "",
    "synonyms": []
  },
  {
    "id": "61748",
    "name": "Municipal Court",
    "group": "Contact A City Department",
    "intent": "contact",
    "jurisdiction": "city",
    "destination": "form",
    "description": "",
    "synonyms": []
  },
  {
    "id": "61760",
    "name": "Parking System Enterprise",
    "group": "Contact A City Department",
    "intent": "contact",
    "jurisdiction": "city",
    "destination": "form",
    "description": "",
    "synonyms": []
  },
  {
    "id": "61768",
    "name": "Planning Department",
    "group": "Contact A City Department",
    "intent": "contact",
    "jurisdiction": "city",
    "destination": "form",
    "description": "",
    "synonyms": []
  },
  {
    "id": "61776",
    "name": "Procurement Services",
    "group": "Contact A City Department",
    "intent": "contact",
    "jurisdiction": "city",
    "destination": "form",
    "description": "",
    "synonyms": []
  },
  {
    "id": "61777",
    "name": "Public Works",
    "group": "Contact A City Department",
    "intent": "contact",
    "jurisdiction": "city",
    "destination": "form",
    "description": "",
    "synonyms": []
  },
  {
    "id": "61778",
    "name": "Real Estate Services",
    "group": "Contact A City Department",
    "intent": "contact",
    "jurisdiction": "city",
    "destination": "form",
    "description": "",
    "synonyms": []
  },
  {
    "id": "61793",
    "name": "Stormwater Enterprise",
    "group": "Contact A City Department",
    "intent": "contact",
    "jurisdiction": "city",
    "destination": "form",
    "description": "",
    "synonyms": []
  },
  {
    "id": "61800",
    "name": "Traffic Engineering",
    "group": "Contact A City Department",
    "intent": "contact",
    "jurisdiction": "city",
    "destination": "form",
    "description": "",
    "synonyms": []
  },
  {
    "id": "61630",
    "name": "Ambulance Transport Questions",
    "group": "Fire Department",
    "intent": "contact",
    "jurisdiction": "city",
    "destination": "form",
    "description": "",
    "synonyms": []
  },
  {
    "id": "61712",
    "name": "Fire Code Violation or Hazard Report",
    "group": "Fire Department",
    "intent": "report",
    "jurisdiction": "city",
    "destination": "form",
    "description": "",
    "synonyms": []
  },
  {
    "id": "61713",
    "name": "Fire Department As Built",
    "group": "Fire Department",
    "intent": "contact",
    "jurisdiction": "city",
    "destination": "form",
    "description": "",
    "synonyms": []
  },
  {
    "id": "61715",
    "name": "Fire Department Engine Visit",
    "group": "Fire Department",
    "intent": "contact",
    "jurisdiction": "city",
    "destination": "form",
    "description": "",
    "synonyms": []
  },
  {
    "id": "61716",
    "name": "Fire Department General Inquiries",
    "group": "Fire Department",
    "intent": "contact",
    "jurisdiction": "city",
    "destination": "form",
    "description": "",
    "synonyms": []
  },
  {
    "id": "61717",
    "name": "Fire Department Incident Report Request",
    "group": "Fire Department",
    "intent": "report",
    "jurisdiction": "city",
    "destination": "form",
    "description": "",
    "synonyms": []
  },
  {
    "id": "61719",
    "name": "Fire Department Station Tours",
    "group": "Fire Department",
    "intent": "contact",
    "jurisdiction": "city",
    "destination": "form",
    "description": "",
    "synonyms": []
  },
  {
    "id": "63474",
    "name": "Abandoned Vehicles On City Streets",
    "group": "Neighborhood Services/Code Enforcement",
    "intent": "report",
    "jurisdiction": "city",
    "destination": "form",
    "description": "",
    "synonyms": [
      "abandoned vehicle",
      "abandoned vehicles",
      "abandoned car",
      "abandoned cars",
      "junk car",
      "junk cars",
      "junk vehicle",
      "car on street",
      "cars on street",
      "parked on the street",
      "parked on street",
      "hasn't moved"
    ]
  },
  {
    "id": "61734",
    "name": "Ice/Snow Removal on Sidewalks",
    "group": "Neighborhood Services/Code Enforcement",
    "intent": "report",
    "jurisdiction": "city",
    "destination": "form",
    "description": "",
    "synonyms": []
  },
  {
    "id": "61737",
    "name": "Illegal Dumping",
    "group": "Neighborhood Services/Code Enforcement",
    "intent": "report",
    "jurisdiction": "city",
    "destination": "form",
    "description": "",
    "synonyms": [
      "illegal dumping",
      "dumped",
      "trash dumped",
      "mattress",
      "couch",
      "refrigerator"
    ]
  },
  {
    "id": "61750",
    "name": "Neighborhood Services",
    "group": "Neighborhood Services/Code Enforcement",
    "intent": "report",
    "jurisdiction": "city",
    "destination": "form",
    "description": "",
    "synonyms": [
      "tall grass",
      "weeds",
      "overgrown",
      "mow",
      "lawn",
      "nuisance",
      "short-term rental",
      "str",
      "airbnb",
      "vrbo",
      "blight",
      "eyesore"
    ]
  },
  {
    "id": "61754",
    "name": "Noise Complaint",
    "group": "Noise Complaint",
    "intent": "report",
    "jurisdiction": "city",
    "destination": "form",
    "description": "",
    "synonyms": [
      "noise",
      "loud",
      "party",
      "loud music",
      "noise complaint",
      "bass"
    ]
  },
  {
    "id": "61631",
    "name": "Animal Control",
    "group": "Other Requests",
    "intent": "report",
    "jurisdiction": "city",
    "destination": "form",
    "description": "",
    "synonyms": []
  },
  {
    "id": "61634",
    "name": "Barking Dog",
    "group": "Other Requests",
    "intent": "report",
    "jurisdiction": "city",
    "destination": "form",
    "description": "",
    "synonyms": [
      "barking dog",
      "dog barking",
      "dogs barking",
      "neighbor dog"
    ]
  },
  {
    "id": "61700",
    "name": "Creek Week trash collection",
    "group": "Other Requests",
    "intent": "report",
    "jurisdiction": "city",
    "destination": "form",
    "description": "",
    "synonyms": []
  },
  {
    "id": "61722",
    "name": "Fraud, Waste and Abuse by City staff or involving City assets",
    "group": "Other Requests",
    "intent": "report",
    "jurisdiction": "city",
    "destination": "form",
    "description": "",
    "synonyms": []
  },
  {
    "id": "61724",
    "name": "General City Contact",
    "group": "Other Requests",
    "intent": "contact",
    "jurisdiction": "city",
    "destination": "form",
    "description": "",
    "synonyms": []
  },
  {
    "id": "61729",
    "name": "GoCOS! Feedback",
    "group": "Other Requests",
    "intent": "report",
    "jurisdiction": "city",
    "destination": "form",
    "description": "",
    "synonyms": []
  },
  {
    "id": "61730",
    "name": "Graffiti",
    "group": "Other Requests",
    "intent": "report",
    "jurisdiction": "city",
    "destination": "form",
    "description": "",
    "synonyms": [
      "graffiti",
      "tag",
      "tagging",
      "vandalism"
    ]
  },
  {
    "id": "61732",
    "name": "Homelessness Information",
    "group": "Other Requests",
    "intent": "contact",
    "jurisdiction": "city",
    "destination": "form",
    "description": "",
    "synonyms": []
  },
  {
    "id": "61736",
    "name": "Illegal Homeless Camps",
    "group": "Other Requests",
    "intent": "report",
    "jurisdiction": "city",
    "destination": "form",
    "description": "",
    "synonyms": [
      "homeless camp",
      "illegal camp",
      "encampment",
      "tents",
      "tent camp"
    ]
  },
  {
    "id": "61786",
    "name": "Scooter-share complaint",
    "group": "Other Requests",
    "intent": "report",
    "jurisdiction": "city",
    "destination": "form",
    "description": "",
    "synonyms": [
      "scooter",
      "scooters",
      "lime",
      "bird"
    ]
  },
  {
    "id": "61628",
    "name": "Adopt-A-Park/Trail Application",
    "group": "Parks, Recreation and Cultural Services",
    "intent": "permit",
    "jurisdiction": "city",
    "destination": "form",
    "description": "",
    "synonyms": []
  },
  {
    "id": "61629",
    "name": "Adult and Youth Sports",
    "group": "Parks, Recreation and Cultural Services",
    "intent": "contact",
    "jurisdiction": "city",
    "destination": "form",
    "description": "",
    "synonyms": []
  },
  {
    "id": "61650",
    "name": "Community Centers, Therapeutic Recreation, Sertich Ice Center",
    "group": "Parks, Recreation and Cultural Services",
    "intent": "contact",
    "jurisdiction": "city",
    "destination": "form",
    "description": "",
    "synonyms": []
  },
  {
    "id": "66783",
    "name": "Garden of the Gods",
    "group": "Parks, Recreation and Cultural Services",
    "intent": "contact",
    "jurisdiction": "city",
    "destination": "form",
    "description": "",
    "synonyms": []
  },
  {
    "id": "61725",
    "name": "General Contact for Parks, Recreation and Cultural Services",
    "group": "Parks, Recreation and Cultural Services",
    "intent": "contact",
    "jurisdiction": "city",
    "destination": "form",
    "description": "",
    "synonyms": []
  },
  {
    "id": "61761",
    "name": "Park Maintenance",
    "group": "Parks, Recreation and Cultural Services",
    "intent": "contact",
    "jurisdiction": "city",
    "destination": "form",
    "description": "",
    "synonyms": []
  },
  {
    "id": "61765",
    "name": "Pikes Peak - America's Mountain",
    "group": "Parks, Recreation and Cultural Services",
    "intent": "contact",
    "jurisdiction": "city",
    "destination": "form",
    "description": "",
    "synonyms": []
  },
  {
    "id": "61790",
    "name": "Special Events",
    "group": "Parks, Recreation and Cultural Services",
    "intent": "contact",
    "jurisdiction": "city",
    "destination": "form",
    "description": "",
    "synonyms": []
  },
  {
    "id": "61802",
    "name": "Trail Maintenance",
    "group": "Parks, Recreation and Cultural Services",
    "intent": "contact",
    "jurisdiction": "city",
    "destination": "form",
    "description": "",
    "synonyms": []
  },
  {
    "id": "61649",
    "name": "Commercial Motor Vehicle Complaints",
    "group": "Police",
    "intent": "report",
    "jurisdiction": "city",
    "destination": "form",
    "description": "",
    "synonyms": []
  },
  {
    "id": "61651",
    "name": "Complaint about a CSPD Employee",
    "group": "Police",
    "intent": "report",
    "jurisdiction": "city",
    "destination": "form",
    "description": "",
    "synonyms": []
  },
  {
    "id": "61652",
    "name": "Compliment about a CSPD Employee",
    "group": "Police",
    "intent": "contact",
    "jurisdiction": "city",
    "destination": "form",
    "description": "",
    "synonyms": []
  },
  {
    "id": "61727",
    "name": "General Questions for the CSPD",
    "group": "Police",
    "intent": "contact",
    "jurisdiction": "city",
    "destination": "form",
    "description": "",
    "synonyms": []
  },
  {
    "id": "61749",
    "name": "Neighborhood Parking Complaints",
    "group": "Police",
    "intent": "report",
    "jurisdiction": "city",
    "destination": "form",
    "description": "",
    "synonyms": [
      "blocking my driveway",
      "blocking driveway",
      "blocking the driveway",
      "parked in front of",
      "parked too close",
      "illegally parked",
      "parking complaint",
      "parking issue",
      "parking problem"
    ]
  },
  {
    "id": "61753",
    "name": "Neighborhood Speeding or General Traffic Complaint",
    "group": "Police",
    "intent": "report",
    "jurisdiction": "city",
    "destination": "form",
    "description": "",
    "synonyms": [
      "speeding",
      "speeders",
      "neighborhood speeding",
      "traffic complaint"
    ]
  },
  {
    "id": "61771",
    "name": "Police Non Emergency",
    "group": "Police",
    "intent": "report",
    "jurisdiction": "city",
    "destination": "form",
    "description": "",
    "synonyms": [
      "police non emergency",
      "non-emergency police",
      "suspicious",
      "suspicious person"
    ]
  },
  {
    "id": "61785",
    "name": "School zone speeding complaint",
    "group": "Police",
    "intent": "report",
    "jurisdiction": "city",
    "destination": "form",
    "description": "",
    "synonyms": []
  },
  {
    "id": "61799",
    "name": "Tow Companies Contact CSPD",
    "group": "Police",
    "intent": "report",
    "jurisdiction": "city",
    "destination": "form",
    "description": "",
    "synonyms": []
  },
  {
    "id": "61510",
    "name": "2C Question/Concern",
    "group": "Roads and Sidewalks",
    "intent": "contact",
    "jurisdiction": "city",
    "destination": "form",
    "description": "",
    "synonyms": []
  },
  {
    "id": "61704",
    "name": "Curb & Gutter Damage",
    "group": "Roads and Sidewalks",
    "intent": "report",
    "jurisdiction": "city",
    "destination": "form",
    "description": "",
    "synonyms": []
  },
  {
    "id": "61706",
    "name": "Deceased Animal on City streets",
    "group": "Roads and Sidewalks",
    "intent": "report",
    "jurisdiction": "city",
    "destination": "form",
    "description": "",
    "synonyms": [
      "dead animal",
      "deceased animal",
      "roadkill",
      "animal carcass"
    ]
  },
  {
    "id": "61341",
    "name": "Pothole",
    "group": "Roads and Sidewalks",
    "intent": "report",
    "jurisdiction": "city",
    "destination": "form",
    "description": "",
    "synonyms": [
      "pothole",
      "potholes",
      "hole in the road",
      "hole in the street"
    ]
  },
  {
    "id": "61780",
    "name": "Repaving Request",
    "group": "Roads and Sidewalks",
    "intent": "report",
    "jurisdiction": "city",
    "destination": "form",
    "description": "",
    "synonyms": []
  },
  {
    "id": "61783",
    "name": "Request a Pedestrian Curb Ramp",
    "group": "Roads and Sidewalks",
    "intent": "report",
    "jurisdiction": "city",
    "destination": "form",
    "description": "",
    "synonyms": []
  },
  {
    "id": "61787",
    "name": "Sidewalk Damage",
    "group": "Roads and Sidewalks",
    "intent": "report",
    "jurisdiction": "city",
    "destination": "form",
    "description": "",
    "synonyms": [
      "sidewalk",
      "cracked sidewalk",
      "sidewalk damage",
      "broken sidewalk",
      "uneven sidewalk"
    ]
  },
  {
    "id": "61789",
    "name": "Snow removal on City streets",
    "group": "Roads and Sidewalks",
    "intent": "report",
    "jurisdiction": "city",
    "destination": "form",
    "description": "",
    "synonyms": [
      "snow removal",
      "snow plow",
      "unplowed",
      "ice on road",
      "ice on street"
    ]
  },
  {
    "id": "61794",
    "name": "Street Debris",
    "group": "Roads and Sidewalks",
    "intent": "report",
    "jurisdiction": "city",
    "destination": "form",
    "description": "",
    "synonyms": []
  },
  {
    "id": "61798",
    "name": "Street Sweeping Request",
    "group": "Roads and Sidewalks",
    "intent": "report",
    "jurisdiction": "city",
    "destination": "form",
    "description": "",
    "synonyms": []
  },
  {
    "id": "61801",
    "name": "Traffic Issues",
    "group": "Roads and Sidewalks",
    "intent": "report",
    "jurisdiction": "city",
    "destination": "form",
    "description": "",
    "synonyms": []
  },
  {
    "id": "61636",
    "name": "Broken Limb/Hanger",
    "group": "Trees",
    "intent": "report",
    "jurisdiction": "city",
    "destination": "form",
    "description": "",
    "synonyms": []
  },
  {
    "id": "61708",
    "name": "Down Limbs",
    "group": "Trees",
    "intent": "report",
    "jurisdiction": "city",
    "destination": "form",
    "description": "",
    "synonyms": []
  },
  {
    "id": "61709",
    "name": "Down Tree",
    "group": "Trees",
    "intent": "report",
    "jurisdiction": "city",
    "destination": "form",
    "description": "",
    "synonyms": []
  },
  {
    "id": "61728",
    "name": "General Tree Service Requests",
    "group": "Trees",
    "intent": "report",
    "jurisdiction": "city",
    "destination": "form",
    "description": "",
    "synonyms": [
      "tree",
      "broken branch",
      "dead tree",
      "tree service"
    ]
  },
  {
    "id": "61763",
    "name": "Permit to plant a tree in City right-of-way",
    "group": "Trees",
    "intent": "permit",
    "jurisdiction": "city",
    "destination": "form",
    "description": "",
    "synonyms": []
  },
  {
    "id": "61764",
    "name": "Permit to work on a City tree",
    "group": "Trees",
    "intent": "permit",
    "jurisdiction": "city",
    "destination": "form",
    "description": "",
    "synonyms": []
  },
  {
    "id": "61637",
    "name": "Broken Sprinkler/Watering Issue",
    "group": "Water & Stormwater",
    "intent": "report",
    "jurisdiction": "city",
    "destination": "form",
    "description": "",
    "synonyms": []
  },
  {
    "id": "61721",
    "name": "Flooding",
    "group": "Water & Stormwater",
    "intent": "report",
    "jurisdiction": "city",
    "destination": "form",
    "description": "",
    "synonyms": [
      "flooding",
      "flood",
      "water in street",
      "standing water",
      "drainage"
    ]
  },
  {
    "id": "61772",
    "name": "Pond Maintenance",
    "group": "Water & Stormwater",
    "intent": "report",
    "jurisdiction": "city",
    "destination": "form",
    "description": "",
    "synonyms": []
  },
  {
    "id": "61791",
    "name": "Spills",
    "group": "Water & Stormwater",
    "intent": "report",
    "jurisdiction": "city",
    "destination": "form",
    "description": "",
    "synonyms": []
  },
  {
    "id": "61792",
    "name": "Storm Drain Maintenance",
    "group": "Water & Stormwater",
    "intent": "report",
    "jurisdiction": "city",
    "destination": "form",
    "description": "",
    "synonyms": []
  },
  {
    "id": "61696",
    "name": "Contracting / Procurement - Inquiries and CORA Requests",
    "group": "Colorado Open Records Act Requests (CORA)",
    "intent": "records",
    "jurisdiction": "city",
    "destination": "form",
    "description": "Purchasing, bid, and contract records requests. Colorado Open Records Act request. Response within 3 working days (up to 7 additional days with cause). Fees: $0.25 per printed pag…",
    "synonyms": []
  },
  {
    "id": "61714",
    "name": "Fire Department CORA Request",
    "group": "Colorado Open Records Act Requests (CORA)",
    "intent": "records",
    "jurisdiction": "city",
    "destination": "form",
    "description": "CORA requests for Property and Environmental Site Assessments. Colorado Open Records Act request. Response within 3 working days (up to 7 additional days with cause). Fees: $0.25 …",
    "synonyms": []
  },
  {
    "id": "61726",
    "name": "General CORA Request",
    "group": "Colorado Open Records Act Requests (CORA)",
    "intent": "records",
    "jurisdiction": "city",
    "destination": "form",
    "description": "General Colorado Open Records Act request for City records. Colorado Open Records Act request. Response within 3 working days (up to 7 additional days with cause). Fees: $0.25 per…",
    "synonyms": [
      "cora",
      "open records",
      "records request",
      "public records",
      "aggregate data",
      "dataset",
      "data request",
      "open data",
      "statistics",
      "how many",
      "year over year",
      "public data"
    ]
  },
  {
    "id": "61752",
    "name": "Neighborhood Services CORA Request",
    "group": "Colorado Open Records Act Requests (CORA)",
    "intent": "records",
    "jurisdiction": "city",
    "destination": "form",
    "description": "Colorado Open Records Act requests for the City Neighborhood Services department regarding Code Enforcement and Zoning Violations. Colorado Open Records Act request. Response with…",
    "synonyms": []
  },
  {
    "id": "61767",
    "name": "Planning Department CORA Request",
    "group": "Colorado Open Records Act Requests (CORA)",
    "intent": "records",
    "jurisdiction": "city",
    "destination": "form",
    "description": "Planning Department records (site plans, rezoning files, variance decisions). Colorado Open Records Act request. Response within 3 working days (up to 7 additional days with cause…",
    "synonyms": []
  },
  {
    "id": "cora-police-records",
    "name": "Police Records CORA Request",
    "group": "Colorado Open Records Act Requests (CORA)",
    "intent": "records",
    "jurisdiction": "city",
    "destination": "email",
    "description": "Crash reports, incident reports, body camera footage, and other CSPD records. Colorado Open Records Act request. Response within 3 working days (up to 7 additional days with cause…",
    "synonyms": [
      "cora police",
      "police cora",
      "crash report cora",
      "incident report cora",
      "body camera cora",
      "police data",
      "crime data",
      "crime stats",
      "crime statistics",
      "police statistics",
      "police numbers",
      "aggregate police"
    ]
  },
  {
    "id": "cora-municipal-court",
    "name": "Municipal Court Records CORA Request",
    "group": "Colorado Open Records Act Requests (CORA)",
    "intent": "records",
    "jurisdiction": "city",
    "destination": "email",
    "description": "Municipal Court case records, citations, and violation history. Colorado Open Records Act request. Response within 3 working days (up to 7 additional days with cause). Fees: $0.25…",
    "synonyms": [
      "municipal court cora",
      "court records",
      "citation records",
      "violation history",
      "municipal court data",
      "court statistics"
    ]
  },
  {
    "id": "cora-utilities",
    "name": "Colorado Springs Utilities Records (CORA)",
    "group": "Colorado Open Records Act Requests (CORA)",
    "intent": "records",
    "jurisdiction": "utility",
    "destination": "external",
    "description": "Records requests for Colorado Springs Utilities (gas, electric, water, wastewater) are handled by CSU directly, not by the City. Response times and fees are set by CSU policy.",
    "synonyms": [
      "utilities cora",
      "csu cora",
      "electric records",
      "water records",
      "gas records",
      "utility data",
      "csu data"
    ]
  },
  {
    "id": "cora-general-contact",
    "name": "General CORA Office (Communications)",
    "group": "Colorado Open Records Act Requests (CORA)",
    "intent": "records",
    "jurisdiction": "city",
    "destination": "email",
    "description": "Not sure where to send a CORA request? Start with City Communications and they will route it. Colorado Open Records Act request. Response within 3 working days (up to 7 additional…",
    "synonyms": []
  },
  {
    "id": "permit-pprbd",
    "name": "Residential Building Permits (PPRBD)",
    "group": "Permits, Licenses & Records",
    "intent": "permit",
    "jurisdiction": "regional",
    "destination": "external",
    "description": "Decks, roofs, basement finishes, water heaters, HVAC, electrical, plumbing, additions, sheds, fences. Handled by Pikes Peak Regional Building Department — a separate agency from t…",
    "synonyms": [
      "deck",
      "roof",
      "roofing",
      "water heater",
      "hvac",
      "furnace",
      "air conditioning",
      "basement",
      "finish basement",
      "electrical",
      "plumbing",
      "mechanical"
    ]
  },
  {
    "id": "permit-neighborhood-enforcement",
    "name": "Code Enforcement Case Lookup",
    "group": "Permits, Licenses & Records",
    "intent": "report",
    "jurisdiction": "city",
    "destination": "external",
    "description": "Look up existing code-enforcement cases, zoning complaints, nuisance violations. To file a new complaint, use \"Neighborhood Services\" in the Report a Problem section.",
    "synonyms": []
  },
  {
    "id": "permit-public-works",
    "name": "Right-of-Way, Traffic Control & Special Events",
    "group": "Permits, Licenses & Records",
    "intent": "permit",
    "jurisdiction": "city",
    "destination": "external",
    "description": "Right-of-way work, traffic control plans, parades, races, block parties, street closures. Issued by Public Works through Accela.",
    "synonyms": [
      "right-of-way",
      "right of way",
      "row permit",
      "traffic control",
      "road closure",
      "parade",
      "race",
      "5k",
      "10k",
      "marathon",
      "block party",
      "special event"
    ]
  },
  {
    "id": "permit-business-licensing",
    "name": "Business License (new, renewal, change)",
    "group": "Permits, Licenses & Records",
    "intent": "permit",
    "jurisdiction": "city",
    "destination": "external",
    "description": "City business licenses for retail, restaurants, contractors, salons, vendors, and regulated businesses. Liquor and cannabis licensing is handled separately.",
    "synonyms": [
      "business license",
      "start a business",
      "open a business",
      "coffee shop",
      "restaurant",
      "retail",
      "store license",
      "shop license",
      "license renewal",
      "vendor",
      "food truck",
      "mobile vendor"
    ]
  },
  {
    "id": "permit-police-records",
    "name": "Crash Reports, Background Checks, Clearance Letters",
    "group": "Permits, Licenses & Records",
    "intent": "permit",
    "jurisdiction": "city",
    "destination": "external",
    "description": "Order a crash report, request a background check, or obtain a clearance letter from the Colorado Springs Police Department.",
    "synonyms": [
      "crash report",
      "accident report",
      "background check",
      "clearance letter",
      "police records",
      "arrest record",
      "incident report",
      "body cam",
      "body camera",
      "theft report",
      "car accident",
      "hit and run"
    ]
  },
  {
    "id": "permit-planning",
    "name": "Zoning, Subdivision, Land Use (Planning)",
    "group": "Permits, Licenses & Records",
    "intent": "permit",
    "jurisdiction": "city",
    "destination": "external",
    "description": "Rezoning, subdivision plats, conditional use, variances, annexation. Commercial and development scale — not home remodels.",
    "synonyms": [
      "zoning",
      "rezone",
      "rezoning",
      "subdivision",
      "plat",
      "land use",
      "conditional use",
      "variance",
      "annexation",
      "comprehensive plan",
      "overlay",
      "setback"
    ]
  },
  {
    "id": "permit-fire-commercial",
    "name": "Commercial Fire Permits (alarms, sprinklers, hazmat)",
    "group": "Permits, Licenses & Records",
    "intent": "permit",
    "jurisdiction": "city",
    "destination": "external",
    "description": "Commercial plan review, fire alarms, sprinklers, hazardous materials, commercial kitchens, assembly permits.",
    "synonyms": [
      "fire permit",
      "fire alarm",
      "sprinkler",
      "sprinkler system",
      "hazmat",
      "hazardous material",
      "commercial kitchen",
      "hood suppression",
      "fire inspection",
      "fire marshal",
      "commercial plan review",
      "assembly permit"
    ]
  },
  {
    "id": "permit-stormwater",
    "name": "Stormwater & Erosion Control (construction sites)",
    "group": "Permits, Licenses & Records",
    "intent": "permit",
    "jurisdiction": "city",
    "destination": "external",
    "description": "Erosion & sediment control plans, stormwater management plans, outfall compliance. Mostly for active construction sites.",
    "synonyms": [
      "stormwater",
      "storm water",
      "erosion",
      "erosion control",
      "sediment",
      "runoff",
      "outfall",
      "swmp",
      "construction site",
      "grading",
      "bmp",
      "best management practice"
    ]
  },
  {
    "id": "permit-infrastructure",
    "name": "Infrastructure Permits (excavation, ROW, utilities)",
    "group": "Permits, Licenses & Records",
    "intent": "permit",
    "jurisdiction": "city",
    "destination": "external",
    "description": "Concrete, excavation, CSU utility permits, telecom/fiber, trenching, boring — infrastructure work, NOT residential.",
    "synonyms": [
      "excavation",
      "utility permit",
      "csu permit",
      "concrete permit",
      "infrastructure permit",
      "public infrastructure",
      "telecom",
      "fiber",
      "conduit",
      "trench",
      "boring"
    ]
  },
  {
    "id": "epc-ph-air-quality",
    "name": "Air Quality",
    "group": "El Paso County — Environmental Health",
    "intent": "permit",
    "jurisdiction": "county",
    "destination": "external",
    "description": "Environmental air monitoring and regulation in El Paso County. Contact Environmental Health at (719) 578-3199 or healthinfo@elpasoco.com.",
    "synonyms": []
  },
  {
    "id": "epc-ph-body-art",
    "name": "Body Art Facility Licensing",
    "group": "El Paso County — Environmental Health",
    "intent": "permit",
    "jurisdiction": "county",
    "destination": "external",
    "description": "Licensing and inspection of tattoo, piercing, and body art facilities. Contact Environmental Health at (719) 578-3199 or healthinfo@elpasoco.com.",
    "synonyms": []
  },
  {
    "id": "epc-ph-child-care",
    "name": "Child Care Facility Licensing",
    "group": "El Paso County — Environmental Health",
    "intent": "permit",
    "jurisdiction": "county",
    "destination": "external",
    "description": "Licensing and inspections of child care facilities in El Paso County. Contact Environmental Health at (719) 578-3199 or healthinfo@elpasoco.com.",
    "synonyms": []
  },
  {
    "id": "epc-ph-construction-land-use",
    "name": "Construction & Land Use Public Health Review",
    "group": "El Paso County — Environmental Health",
    "intent": "permit",
    "jurisdiction": "county",
    "destination": "external",
    "description": "Public health reviews for construction projects and land-use approvals. Contact Environmental Health at (719) 578-3199 or healthinfo@elpasoco.com.",
    "synonyms": []
  },
  {
    "id": "epc-ph-construction-activity",
    "name": "Construction Activity Permit",
    "group": "El Paso County — Environmental Health",
    "intent": "permit",
    "jurisdiction": "county",
    "destination": "external",
    "description": "Permitting for specific construction activities that affect public health. Contact Environmental Health at (719) 578-3199 or healthinfo@elpasoco.com.",
    "synonyms": []
  },
  {
    "id": "epc-ph-owts",
    "name": "Septic System Permits (OWTS)",
    "group": "El Paso County — Environmental Health",
    "intent": "permit",
    "jurisdiction": "county",
    "destination": "external",
    "description": "Onsite Wastewater Treatment System permits and oversight — required outside city sewer service. Contact Environmental Health at (719) 578-3199 or healthinfo@elpasoco.com.",
    "synonyms": []
  },
  {
    "id": "epc-ph-open-burning",
    "name": "Open Burning Permit",
    "group": "El Paso County — Environmental Health",
    "intent": "permit",
    "jurisdiction": "county",
    "destination": "external",
    "description": "Regulation of open burning in unincorporated El Paso County. Contact Environmental Health at (719) 578-3199 or healthinfo@elpasoco.com.",
    "synonyms": []
  },
  {
    "id": "epc-ph-pools-spas",
    "name": "Public Pool & Spa Licensing",
    "group": "El Paso County — Environmental Health",
    "intent": "permit",
    "jurisdiction": "county",
    "destination": "external",
    "description": "Licensing and inspections for public swimming pools and spas. Contact Environmental Health at (719) 578-3199 or healthinfo@elpasoco.com.",
    "synonyms": []
  },
  {
    "id": "epc-ph-radon",
    "name": "Radon Testing & Assessment",
    "group": "El Paso County — Environmental Health",
    "intent": "records",
    "jurisdiction": "county",
    "destination": "external",
    "description": "Home radon testing kits and assessment services. Contact Environmental Health at (719) 578-3199 or healthinfo@elpasoco.com.",
    "synonyms": []
  },
  {
    "id": "epc-ph-retail-food",
    "name": "Retail Food License (Restaurants & Food Service)",
    "group": "El Paso County — Environmental Health",
    "intent": "permit",
    "jurisdiction": "county",
    "destination": "external",
    "description": "Licensing and inspection of restaurants, food trucks, and retail food establishments. Contact Environmental Health at (719) 578-3199 or healthinfo@elpasoco.com.",
    "synonyms": []
  },
  {
    "id": "epc-ph-water-testing",
    "name": "Drinking Water Testing",
    "group": "El Paso County — Environmental Health",
    "intent": "records",
    "jurisdiction": "county",
    "destination": "external",
    "description": "Private-well and drinking-water quality analysis for residents. Contact Environmental Health at (719) 578-3199 or healthinfo@elpasoco.com.",
    "synonyms": []
  }
];
