#!/usr/bin/env node --experimental-strip-types
/**
 * Compile the portal's topic catalog into a compact form for the Claude
 * prompt. Run once whenever extensions.ts, classifications.json, or
 * keywords.ts changes.
 *
 * Output: worker/catalog.ts (committed, read at cold start by the Worker).
 *
 * Keeps only the fields Claude needs to classify: id, name, group,
 * destination kind, jurisdiction, description (truncated), and the keyword
 * synonyms from the local router so the model sees the same "this phrase
 * means this topic" cues.
 */
import fs from 'node:fs';
import path from 'node:path';
import { fileURLToPath } from 'node:url';

const HERE = path.dirname(fileURLToPath(import.meta.url));
const PROTO = path.resolve(
  HERE,
  '..',
  'microsites',
  'city',
  'goGov',
  'cos-portal-prototype',
  'src',
);

const raw = JSON.parse(
  fs.readFileSync(path.join(PROTO, 'data', 'classifications.json'), 'utf8'),
);
const { mergeExtensions } = await import(
  path.join(PROTO, 'data', 'extensions.ts')
);
const { inferFacets } = await import(path.join(PROTO, 'data', 'facets.ts'));
const { KEYWORD_INDEX } = await import(path.join(PROTO, 'data', 'keywords.ts'));

const groupedRaw = raw.groups.map((g) => ({
  ...g,
  items: g.items.map((t) => ({ ...t })),
}));
const groups = mergeExtensions(groupedRaw).map((g) => ({
  ...g,
  items: g.items.map((t) => ({
    ...t,
    facets: t.facets ?? inferFacets(t, g.groupName),
  })),
}));

// Index keyword synonyms by topicId so we can attach a compact hint list
const keywordsByTopic = {};
for (const entry of KEYWORD_INDEX) {
  if (!keywordsByTopic[entry.topicId]) keywordsByTopic[entry.topicId] = [];
  keywordsByTopic[entry.topicId].push(...entry.keywords);
}

function truncate(s, n = 180) {
  if (!s) return '';
  const cleaned = s.replace(/\s+/g, ' ').trim();
  return cleaned.length > n ? cleaned.slice(0, n - 1) + '…' : cleaned;
}

const out = [];
for (const g of groups) {
  for (const t of g.items) {
    const dest = t.destination?.kind ?? 'form';
    const jur = t.facets?.jurisdiction ?? 'city';
    const intent = t.facets?.intent ?? 'contact';
    const synonyms = (keywordsByTopic[t.topicId] ?? []).slice(0, 12);
    out.push({
      id: t.topicId,
      name: t.name,
      group: g.groupName,
      intent,
      jurisdiction: jur,
      destination: dest,
      description: truncate(t.description),
      synonyms,
    });
  }
}

const header = `// AUTO-GENERATED by worker/generate-catalog.mjs. Do not edit by hand.
// Regenerate with: node --experimental-strip-types worker/generate-catalog.mjs

export interface CatalogTopic {
  id: string;
  name: string;
  group: string;
  intent: string;
  jurisdiction: string;
  destination: string;
  description: string;
  synonyms: string[];
}

export const CATALOG: CatalogTopic[] = `;

const body = JSON.stringify(out, null, 2);

fs.writeFileSync(
  path.join(HERE, 'catalog.ts'),
  header + body + ';\n',
  'utf8',
);

console.log(`Wrote worker/catalog.ts · ${out.length} topics`);
